[package]
name = "sam_sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
serial_test="0.7"

[build-dependencies]
bindgen = "0.53.1"
cc = "1.0"
